[package]
edition = "2024"
name = "crust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.14.3"
log = "0.4.29"
simple_logger = "5.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.49.0"
